### ISSUE TITLE
add cuml solver

### ISSUE THREAD

**Issue by agramfort** [benchopt/benchmark_lasso#60]
https://docs.rapids.ai/api/cuml/stable/api.html#lasso-regression

**Comment by tanglef** [comment]
Cuml is a tricky one, I don't know if it makes sense to add it (other than informative value):

- they advertise their speedup (up to 300x against sklearn cpu) with their benchmarks [reproducible here](https://github.com/rapidsai/cuml/blob/branch-22.06/notebooks/tools/cuml_benchmarks.ipynb) but they only test it on cases where n<p (and in the doc say that `qn` solver will perform better than `cd` when p>n (which we see when running it with benchopt
- However when p>>n it is very very slow... And technically it is the use case of the LASSO... So wdyt ?

| leukemia | simulated n<<p | simulated n >> p|
| ---------- | ------------- | ---------------- |
|![Capture d’écran de 2022-05-12 11-10-31](https://user-images.githubusercontent.com/57089823/168036118-5342440a-211f-416e-8605-8e12c24c8867.png)|![Capture d’écran de 2022-05-12 11-10-56](https://user-images.githubusercontent.com/57089823/168035927-0e6883ae-e14d-40fb-be2c-b38c757a1e52.png) | ![Capture d’écran de 2022-05-12 11-10-44](https://user-images.githubusercontent.com/57089823/168035959-53cac1f9-bdd3-4391-a04d-cfc462607f4b.png) |

poke @mathurinm too

**Comment by mathurinm** [comment]
Is there a typo "they only test it on cases where n<p" instead of "n > p" ?
![image](https://user-images.githubusercontent.com/8993218/168037655-e24e937c-7aba-483b-a64d-cfb54a2e65ba.png)

QN is for quasi newton ?

If it works the PR can be merged regardless of the perf, no ? That's the goal of benchopt

**Comment by tanglef** [comment]
Yes sorry they test it for a lot of samples, few features (the values I put in the third plot)

**Comment by tanglef** [comment]
And yes, qn is for quasi newton

**Comment by tanglef** [comment]
> If it works the PR can be merged regardless of the perf, no ? That's the goal of benchopt

The thing is, we don't use a case where n>p in the default run values (at least I think so), so we never showcase their speedup...

**Comment by mathurinm** [comment]
Johan is adding one in https://github.com/benchopt/benchmark_lasso/pull/90

and users may decide to change the default values anyways, so I'm in favor of adding it. The goal is not to showcase their speedups, it is to make it easy for the community to test it

**Comment by agramfort** [comment]
Saying that CUML does not work so far very well is interesting ! We can decide not to show it but just to write it in the paper. We have 8 pages to fill with text so English remains a good way to express results :)

**Comment by tanglef** [comment]
To make sure these problems with sizes are not from our side, this is some settings I tested with their `benchmarking` function
(note that they use a default value for the penalty, not indicated, simulated dataset and the cpu time is made internally in the same function using a  scikit-learn call)
To make it useful, we indeed seem to observer that there is no speedup if the data is too small or n < p. 

![Capture d’écran de 2022-05-12 21-28-08](https://user-images.githubusercontent.com/57089823/168153474-62389fdd-05dd-4540-8ec7-57212bcaa099.png)
