### ISSUE TITLE
[DOC] Different intructions in the Readme.rst and on the doc

### ISSUE THREAD

**Issue by ngazagna** [benchopt/benchmark_lasso#73]
To get back in touch with benchopt I followed instructions on the benchmark_lasso repo. 
On the readme it is suggested to run
```
$ git clone https://github.com/benchopt/benchmark_lasso
$ benchopt run ./benchmark_lasso
```

Whereas everywhere else (on the benchopt repo and on the documentation) it is said to run
```
$ benchopt install --env ./benchmark_logreg_l2
$ benchopt run --env ./benchmark_logreg_l2
```

**Comment by mathurinm** [comment]
Do you think it would be better to add the `-- env` option in this repo's readme command ?
