### ISSUE TITLE
ENH Missing references

### ISSUE THREAD

**Issue by josephsalmon** [benchopt/benchmark_lasso#95]
A proper reference or url for the glum solver is missing:
https://github.com/benchopt/benchmark_lasso/blob/75648315b31713fe9235ed6bfa6d2da65a2bc32c/solvers/glum.py#L14
ping: @tbng

**Comment by josephsalmon** [comment]
actually the same is true for:
- noncvx_pro
- snapml
ping also @tanglef

**Comment by tanglef** [comment]
Let's make a list
- [ ]  glum
- [ ]  snapml
- [ ]  cuml
- [ ]  noncvxpro

**Comment by mathurinm** [comment]
There is no reference for glum, the rest have been addressed. thanks @tanglef
